# action.yaml
name: 'Cortex GitHub Action'
description: 'A GitHub Action that creates a Deploy Event in a Service in Cortex'
inputs:
  num:
    description: 'Enter your Cortex API Token'
    required: true
    default: "1"
runs:
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Add Deploy Event
      id: add-deploy
      run: python src/deploy.py
      shell: bash